setup:
  simpler:
    testfile: ./scenarios/simpler.toml
    min_balance: 12.1
  uniV2:
    testfile: ./scenarios/uniV2.toml
    rpc_url: http://localhost:8545 # Optional
    min_balance: "11"
    env:
      - Key1=Valu1
      - Key2=Valu2
    private_keys: # Optional (these Private keys are from Anvil)
      - 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
      - 0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d
    tx_type: eip1559  # Optional

spam:
  stages:
    warmup:
      - testfile: ./scenarios/simpler.toml
        tps: 3
        duration: 3
        loop: 2
      - testfile: ./scenarios/simpler.toml
        tps: 3
        duration: 3
        loop: 2
      - testfile: ./testfiles/simpler.toml
        tps: 3
        duration: 3
        loop: 2
      - testfile: ./testfiles/uniV2.toml
        tps: 2
        duration: 3
    medium:
      - testfile: ./testfiles/simpler.toml
        tps: 10
        duration: 2