use alloy::hex;
use clap::Subcommand;
use contender_core::generator::seeder::SeedValue;
use std::path::PathBuf;
use contender_core::generator::{RandSeed, seeder::Seeder};
use contender_core::db::DbOps;
use crate::util::data_dir;
use alloy_primitives::Address;
use alloy_signer::k256;
use contender_testfile;

#[derive(Debug, Subcommand)]
pub enum AdminCommand {
    #[command(
        name = "accounts",
        about = "Print addresses generated by RandSeed for a given from_pool or scenario file"
    )]
    Accounts {
        /// From pool to generate accounts for
        #[arg(short = 'f', long)]
        from_pool: Option<String>,

        /// Scenario file to generate accounts for
        #[arg(short = 's', long)]
        scenario_file: Option<PathBuf>,

        /// Number of signers to generate
        #[arg(short = 'n', long, default_value = "10")]
        num_signers: usize,
    },

    #[command(
        name = "latest-run-id",
        about = "Print the max run id in the DB"
    )]
    LatestRunId,

    #[command(
        name = "seed",
        about = "Print the contents of ~/.contender/seed"
    )]
    Seed,
}

pub async fn handle_admin_command(command: AdminCommand, db: impl DbOps) -> Result<(), Box<dyn std::error::Error>> {
    match command {
        AdminCommand::Accounts { from_pool, scenario_file, num_signers } => {
            let seed_path = format!("{}/seed", data_dir()?);
            let seed_hex = std::fs::read_to_string(&seed_path)?;
            let seed_bytes = hex::decode(seed_hex.trim())?;
            
            let rand_seed = RandSeed::seed_from_bytes(&seed_bytes);
            
            if let Some(pool) = from_pool {
                println!("Accounts for pool '{}':", pool);
                // Generate deterministic addresses using the seed values
                let values = rand_seed.seed_values(num_signers, None, None);
                for (i, value) in values.enumerate() {
                    // Convert the seed value to a private key and derive the address
                    let private_key = value.as_u256();
                    let signing_key = k256::ecdsa::SigningKey::from_bytes((&private_key.to_be_bytes()).into())
                        .expect("Failed to create SigningKey from private key");
                    let address = Address::from_private_key(&signing_key);
                    println!("{}: {}", i, address);
                }
            } else if let Some(scenario_path) = scenario_file {
                // Parse the scenario file to get from_pool declarations
                let test_config = contender_testfile::TestConfig::from_file(scenario_path.to_str().unwrap())?;
                
                // Extract all unique from_pool declarations from the scenario
                let mut pools = std::collections::HashSet::new();
                
                // Check create steps
                if let Some(create_steps) = &test_config.create {
                    for step in create_steps {
                        if let Some(pool) = &step.from_pool {
                            pools.insert(pool.clone());
                        }
                    }
                }
                
                // Check setup steps
                if let Some(setup_steps) = &test_config.setup {
                    for step in setup_steps {
                        if let Some(pool) = &step.from_pool {
                            pools.insert(pool.clone());
                        }
                    }
                }
                
                // Check spam steps
                if let Some(spam_steps) = &test_config.spam {
                    for step in spam_steps {
                        match step {
                            contender_core::generator::types::SpamRequest::Tx(tx) => {
                                if let Some(pool) = &tx.from_pool {
                                    pools.insert(pool.clone());
                                }
                            }
                            contender_core::generator::types::SpamRequest::Bundle(bundle) => {
                                for tx in &bundle.txs {
                                    if let Some(pool) = &tx.from_pool {
                                        pools.insert(pool.clone());
                                    }
                                }
                            }
                        }
                    }
                }
                
                // Generate and print accounts for each pool
                for pool in pools {
                    println!("\nAccounts for pool '{}':", pool);
                    let values = rand_seed.seed_values(num_signers, None, None);
                    for (i, value) in values.enumerate() {
                        let private_key = value.as_u256();
                        let signing_key = k256::ecdsa::SigningKey::from_bytes((&private_key.to_be_bytes()).into())
                            .expect("Failed to create SigningKey from private key");
                        let address = Address::from_private_key(&signing_key);
                        println!("{}: {}", i, address);
                    }
                }
            } else {
                println!("Either --from-pool or --scenario-file must be provided");
            }
        },
        AdminCommand::LatestRunId => {
            let num_runs = db.num_runs()?;
            println!("Latest run ID: {}", num_runs);
        },
        AdminCommand::Seed => {
            let seed_path = format!("{}/seed", data_dir()?);
            let seed = std::fs::read_to_string(&seed_path)?;
            println!("{}", seed.trim());
        },
    }
    Ok(())
} 