//! Build script that generates `static/builtin_scenarios.js` — a JavaScript
//! constant describing the parameter schema for every builtin scenario.
//!
//! Uses `syn` to parse the actual Rust token stream from the CLI crate,
//! extracting field names, types, defaults, and help text from `#[arg(...)]`
//! attributes and doc comments.

use std::collections::HashMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use quote::ToTokens;
use syn::{Attribute, Expr, Fields, Item, Lit, Meta, Type};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let cli_dir = manifest_dir
        .parent()
        .unwrap()
        .join("cli/src/default_scenarios");

    // (UI name, source file relative to cli_dir, struct name)
    let scenarios: &[(&str, &str, &str)] = &[
        ("Blobs", "blobs.rs", "BlobsCliArgs"),
        ("Contract", "custom_contract.rs", "CustomContractCliArgs"),
        (
            "EthFunctions",
            "eth_functions/command.rs",
            "EthFunctionsCliArgs",
        ),
        ("Erc20", "erc20.rs", "Erc20CliArgs"),
        ("FillBlock", "fill_block.rs", "FillBlockCliArgs"),
        ("Revert", "revert.rs", "RevertCliArgs"),
        ("SetCode", "setcode/base.rs", "SetCodeCliArgs"),
        ("Storage", "storage.rs", "StorageStressCliArgs"),
        ("Stress", "stress.rs", "StressCliArgs"),
        ("Transfers", "transfers.rs", "TransferStressCliArgs"),
        ("UniV2", "uni_v2.rs", "UniV2CliArgs"),
    ];

    let enum_files: &[(&str, &str)] = &[
        ("EthereumOpcode", "eth_functions/opcodes.rs"),
        ("EthereumPrecompile", "eth_functions/precompiles.rs"),
    ];

    let enum_variants = parse_enum_files(&cli_dir, enum_files);

    let mut js =
        String::from("// AUTO-GENERATED by build.rs — do not edit\nconst BUILTIN_SCENARIOS = {\n");

    for (name, file, struct_name) in scenarios {
        let path = cli_dir.join(file);
        println!("cargo:rerun-if-changed={}", path.display());

        let source = fs::read_to_string(&path).unwrap_or_else(|e| {
            panic!("Failed to read {}: {e}", path.display());
        });
        let ast = syn::parse_file(&source).unwrap_or_else(|e| {
            panic!("Failed to parse {}: {e}", path.display());
        });

        let fields = extract_fields(&ast, struct_name, &enum_variants);

        let key = to_kebab_case(name);
        js.push_str(&format!("  \"{key}\": [\n"));
        for f in &fields {
            js.push_str(&format!(
                "    {{ name: {}, type: {}, default: {}, help: {}, optional: {} }},\n",
                js_str(&f.name),
                js_str(&f.field_type),
                js_opt(&f.default),
                js_opt(&f.help),
                if f.optional { "true" } else { "false" },
            ));
        }
        js.push_str("  ],\n");
    }
    js.push_str("};\n");

    let static_dir = manifest_dir.join("static");
    fs::create_dir_all(&static_dir).unwrap();
    fs::write(static_dir.join("builtin_scenarios.js"), &js).unwrap();

    println!("cargo:rerun-if-changed=build.rs");
}

// ── types ────────────────────────────────────────────────────────────

#[derive(Debug)]
struct FieldInfo {
    name: String,
    field_type: String,
    default: Option<String>,
    help: Option<String>,
    optional: bool,
}

// ── JS helpers ───────────────────────────────────────────────────────

/// Convert PascalCase to kebab-case to match `#[serde(rename_all = "kebab-case")]`.
fn to_kebab_case(s: &str) -> String {
    let mut result = String::new();
    let chars: Vec<char> = s.chars().collect();
    for (i, &c) in chars.iter().enumerate() {
        if c.is_uppercase() && i > 0 {
            let prev = chars[i - 1];
            if prev.is_lowercase() || prev.is_ascii_digit() {
                result.push('-');
            } else if i + 1 < chars.len() && chars[i + 1].is_lowercase() {
                result.push('-');
            }
        }
        result.push(c.to_ascii_lowercase());
    }
    result
}

fn js_str(s: &str) -> String {
    format!(
        "\"{}\"",
        s.replace('\\', "\\\\")
            .replace('"', "\\\"")
            .replace('\n', "\\n")
            .replace('\r', "\\r")
    )
}

fn js_opt(v: &Option<String>) -> String {
    match v {
        Some(s) => js_str(s),
        None => "null".into(),
    }
}

// ── enum parsing ─────────────────────────────────────────────────────

fn parse_enum_files(cli_dir: &Path, enums: &[(&str, &str)]) -> HashMap<String, Vec<String>> {
    let mut map = HashMap::new();
    for (enum_name, file) in enums {
        let path = cli_dir.join(file);
        println!("cargo:rerun-if-changed={}", path.display());
        let source = fs::read_to_string(&path).unwrap_or_default();
        let ast = syn::parse_file(&source).unwrap();
        for item in &ast.items {
            if let Item::Enum(e) = item {
                if e.ident == enum_name {
                    let variants: Vec<String> =
                        e.variants.iter().map(|v| v.ident.to_string()).collect();
                    map.insert(enum_name.to_string(), variants);
                }
            }
        }
    }
    map
}

// ── struct field extraction ──────────────────────────────────────────

fn extract_fields(
    ast: &syn::File,
    struct_name: &str,
    enum_variants: &HashMap<String, Vec<String>>,
) -> Vec<FieldInfo> {
    for item in &ast.items {
        if let Item::Struct(s) = item {
            if s.ident == struct_name {
                return fields_from_struct(s, enum_variants);
            }
        }
    }
    vec![]
}

fn fields_from_struct(
    s: &syn::ItemStruct,
    enum_variants: &HashMap<String, Vec<String>>,
) -> Vec<FieldInfo> {
    let Fields::Named(ref named) = s.fields else {
        return vec![];
    };

    let mut out = Vec::new();

    for field in &named.named {
        // Skip #[command(flatten)] and #[command(subcommand)] fields.
        if has_command_attr(field, "flatten") || has_command_attr(field, "subcommand") {
            continue;
        }

        let name = field
            .ident
            .as_ref()
            .map(|i| i.to_string())
            .unwrap_or_default();

        let raw_ty = type_to_string(&field.ty);
        let optional = raw_ty.starts_with("Option <") || raw_ty.starts_with("Option<");
        let field_type = rust_type_to_js(&raw_ty, enum_variants);

        let arg_attrs = collect_arg_kv(&field.attrs);
        let default = arg_attrs
            .get("default_value")
            .cloned()
            .or_else(|| arg_attrs.get("default_value_t").cloned());
        let help = arg_attrs
            .get("long_help")
            .cloned()
            .or_else(|| arg_attrs.get("help").cloned())
            .or_else(|| doc_comment(&field.attrs));

        out.push(FieldInfo {
            name,
            field_type,
            default,
            help,
            optional,
        });
    }
    out
}

/// Check if a field has `#[command(subcommand)]` or `#[command(flatten)]`.
fn has_command_attr(field: &syn::Field, keyword: &str) -> bool {
    field.attrs.iter().any(|attr| {
        if !attr.path().is_ident("command") {
            return false;
        }
        let tokens = attr.meta.to_token_stream().to_string();
        tokens.contains(keyword)
    })
}

/// Collect key-value pairs from `#[arg(...)]` attributes.
fn collect_arg_kv(attrs: &[Attribute]) -> HashMap<String, String> {
    let mut map = HashMap::new();
    for attr in attrs {
        if !attr.path().is_ident("arg") {
            continue;
        }
        if let Meta::List(list) = &attr.meta {
            let tokens = list.tokens.to_string();
            for segment in split_top_level(&tokens) {
                let segment = segment.trim();
                if let Some((k, v)) = segment.split_once('=') {
                    let k = k.trim();
                    let v = v.trim();
                    // Parse quoted values through syn::LitStr to properly unescape.
                    let value = if v.starts_with('"') {
                        syn::parse_str::<syn::LitStr>(v)
                            .map(|lit| lit.value())
                            .unwrap_or_else(|_| v.to_string())
                    } else {
                        v.to_string()
                    };
                    map.insert(k.to_string(), value);
                }
            }
        }
    }
    map
}

/// Split a token stream string on top-level commas (not inside parens/brackets/quotes).
fn split_top_level(s: &str) -> Vec<String> {
    let mut parts = Vec::new();
    let mut current = String::new();
    let mut depth = 0u32;
    let mut in_string = false;
    let mut prev = '\0';
    for ch in s.chars() {
        if ch == '"' && prev != '\\' {
            in_string = !in_string;
        }
        if !in_string {
            match ch {
                '(' | '[' => depth += 1,
                ')' | ']' => depth = depth.saturating_sub(1),
                ',' if depth == 0 => {
                    parts.push(std::mem::take(&mut current));
                    prev = ch;
                    continue;
                }
                _ => {}
            }
        }
        current.push(ch);
        prev = ch;
    }
    if !current.trim().is_empty() {
        parts.push(current);
    }
    parts
}

/// Extract `/// doc comments` concatenated into a single string.
fn doc_comment(attrs: &[Attribute]) -> Option<String> {
    let docs: Vec<String> = attrs
        .iter()
        .filter_map(|attr| {
            if !attr.path().is_ident("doc") {
                return None;
            }
            if let Meta::NameValue(nv) = &attr.meta {
                if let Expr::Lit(lit) = &nv.value {
                    if let Lit::Str(s) = &lit.lit {
                        return Some(s.value().trim().to_string());
                    }
                }
            }
            None
        })
        .filter(|s| !s.is_empty())
        .collect();
    if docs.is_empty() {
        None
    } else {
        Some(docs.join(" "))
    }
}

fn type_to_string(ty: &Type) -> String {
    ty.to_token_stream().to_string()
}

fn rust_type_to_js(raw: &str, enum_variants: &HashMap<String, Vec<String>>) -> String {
    let inner = raw
        .replace("Option <", "Option<")
        .replace("Vec <", "Vec<")
        .replace("Option<", "")
        .replace("Vec<", "")
        .replace('>', "")
        .replace(' ', "");

    for (enum_name, variants) in enum_variants {
        if inner.contains(enum_name.as_str()) {
            let opts = variants.join(",");
            if raw.contains("Vec") {
                return format!("multi-select:{opts}");
            }
            return format!("select:{opts}");
        }
    }

    match inner.as_str() {
        "bool" => "bool".into(),
        "u32" | "u64" | "i64" | "usize" => "number".into(),
        _ => "text".into(),
    }
}
