on: [push]

jobs:
  preview-report:
    runs-on: ${{ matrix.configs.runner }}
    strategy:
      matrix:
        configs:
        - runner: warp-ubuntu-latest-x64-32x
    
    env:
      DEBUG_USEFILE: true
      BROWSER: none
      C_HOME_PATH: /home/runner/.contender
      C_REPORT_NAME: report-2-2.html

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
    - name: Install deps
      run: sudo apt-get install -y libsqlite3-dev fontconfig libfontconfig1-dev libfontconfig
    - name: Build
      run: cargo build --workspace

    - name: Copy example data
      run: |
        mkdir -p $C_HOME_PATH/reports
        cp -r ./test_fixtures/* $C_HOME_PATH

    - name: Generate report
      run: cargo run -- report http://localhost:8545
    
    - name: Prepare report
      id: prepare-report
      run: |
        # Fix the report path in the generated HTML file
        # TODO: fix report path; I think we actually need https://htmlpreview.github.io/?https://github.com/${owner}/${repo}/blob/${sha}/${htmlFile}
        sed -i "s|$C_HOME_PATH|/github/workspace|g" $C_HOME_PATH/reports/report-*.html
        echo "report_path=/github/workspace/reports/$C_REPORT_NAME" >> "$GITHUB_OUTPUT"

    - name: Upload report
      uses: actions/upload-artifact@v4
      with:
        name: html-report
        path: /home/runner/.contender/reports/report-2-2.html
        retention-days: 10
    - name: Upload heatmap
      uses: actions/upload-artifact@v4
      with:
        name: heatmap-png
        path: "$C_HOME_PATH/reports/heatmap-2-2.png"

    - name: HTML preview
      id: html-preview
      uses: pavi2410/html-preview-action@v4
      with:
        html_file: ${{ steps.prepare-report.outputs.report_path }}
