on: [push]

jobs:
  preview-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build contender image
        id: build-contender
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          tags: contender:latest

      - name: Generate report
        id: gen-report
        uses: ./.github/actions/preview-report

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: workspace_artifacts
          path: ${{ github.workspace }}

      - name: HTML preview
        id: html-preview
        uses: pavi2410/html-preview-action@v4
        with:
          html_file: ${{ steps.gen-report.outputs.report_path }}
